server:
  port: 5000

spring:
  datasource.url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2.console.enabled: true
  data.jpa.repositories.bootstrap-mode: default
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties.hibernate.generate_statistics: true
    properties.hibernate.format_sql: true